org: pedropbaracho
app: my-tdd-service-app
service: my-tdd-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

plugins:
  - serverless-mocha-plugin
